library(plyr)
dados = read.csv("salario.csv")
count(dados, "UF")
count(dados, "Regiao")
profissionaisSudeste =subset(dados,Regiao == "Sudeste")
count(profissionaisSudeste, "UF")
profissionaisMG =subset(dados,UF == "MG")
count(profissionaisMG, "Cidade")
help(read.csv)

count(dados, "Horas.Diarias")
count(dados, "Tempo.de.Empresa")
count(dados, "Experiencia.Profissional")
k = (subset(dados,Tempo.de.Empresa == Experiencia.Profissional))
nrow(k)
